name: Spotify Availability Tracker

on:
  schedule:
    - cron: '0 */3 * * *'  # Roda a cada 3 horas (00:00, 03:00, 06:00...)
  workflow_dispatch:      # Permite que rodes manualmente para testar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/checkout@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run tracker script
        run: python main.py
