name: Spotify Availability Tracker

on:
  schedule:
    - cron: '0 12 * * *' # Roda às 12:00 UTC (09:00 Horário de Brasília)
  workflow_dispatch: # Permite que você rode manualmente se quiser

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run tracker
        run: python main.py
